[tools]
actionlint = "1.7.7"
awscli = "2.24.11"
azure-cli = "2.69.0"
black = "25.1.0"
golang = "1.23.4"
gradle = "8.9"
grype = "0.86.1"
helm = "3.16.4"
java = "openjdk-21.0.2"
kubectl = "1.32.0"
maven = "3.9.9"
nodejs = "22.14.0"
oc = "stable-4.17"
packer = "1.11.2"
pipx = "1.7.1"
"pipx:checkov" = "latest"
"pipx:semgrep" = "latest"
poetry = "latest"
pre-commit = "4.0.1"
python = "3.12.9"
r = "4.4.2"
ripgrep = "14.1.1"
ruff = "0.9.4"
rust = "1.83.0"
scala = "3.6.2"
shellcheck = "0.10.0"
steampipe = "1.0.1"
terraform = "1.10.2"
trivy = "0.58.0"
"ubi:clever/csvlint" = "latest"
uv = "latest"
