[tools]
actionlint = "1.7.7"
awscli = "2.25.7"
azure-cli = "2.71.0"
black = "25.1.0"
golang = "1.24.1"
gradle = "8.13.0"
grype = "0.90.0"
helm = "3.17.2"
java = "openjdk-21.0.2"
kubectl = "1.32.3"
maven = "3.9.9"
nodejs = "22.14.0"
oc = "4.18.7"
packer = "1.12.0"
pipx = "1.7.1"
pipx:checkov = "3.2.395"
pipx:semgrep = "1.116.0"
poetry = "2.1.2"
pre-commit = "4.2.0"
python = "3.12.9"
r = "4.4.3"
ripgrep = "14.1.1"
ruff = "0.11.2"
rust = "1.85.1"
shellcheck = "0.10.0"
steampipe = "1.0.3"
terraform = "1.11.3"
trivy = "0.61.0"
ubi:clever/csvlint = "0.3.0"
uv = "0.6.11"