[tools]
actionlint = "1.7.7"
awscli = "2.24.21"
azure-cli = "2.70.0"
black = "25.1.0"
golang = "1.24.1"
gradle = "8.13.0"
grype = "0.89.0"
helm = "3.17.1"
java = "openjdk-21.0.2"
kubectl = "1.32.2"
maven = "3.9.9"
nodejs = "23.9.0"
oc = "4.18.4"
packer = "1.12.0"
pipx = "1.7.1"
"pipx:checkov" = "latest"
"pipx:semgrep" = "latest"
poetry = "latest"
pre-commit = "4.1.0"
python = "3.12.9"
r = "4.4.3"
ripgrep = "14.1.1"
ruff = "0.9.10"
rust = "1.85.0"
shellcheck = "0.10.0"
steampipe = "1.0.3"
terraform = "1.11.1"
trivy = "0.60.0"
"ubi:clever/csvlint" = "latest"
uv = "latest"