[tools]
actionlint = "latest"
awscli = "latest"
azure-cli = "latest"
black = "latest"
golang = "latest"
gradle = "latest"
grype = "latest"
helm = "latest"
java = "latest"
kubectl = "latest"
maven = "latest"
nodejs = "latest"
oc = "latest"
packer = "latest"
pipx = "latest"
"pipx:checkov" = "latest"
"pipx:semgrep" = "latest"
poetry = "latest"
pre-commit = "latest"
python = "latest"
r = "latest"
ripgrep = "latest"
ruff = "latest"
rust = "latest"
shellcheck = "latest"
steampipe = "latest"
terraform = "latest"
trivy = "latest"
"ubi:clever/csvlint" = "latest"
uv = "latest"
