name: Github Repo Statistics

on:
  schedule:
    # Run this once per day, towards the end of the day for keeping the most
    # recent data point most meaningful (hours are interpreted in UTC).
    - cron: "0 23 * * *"
  workflow_dispatch: # Allow for running this manually.

jobs:
  repostats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    environment:
      name: github-app-ocio-github-repo-statistics
    steps:
      - uses: actions/create-github-app-token@d72941d797fd3113feb6b93fd0dec494b13a2547 # v1.12.0
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: run github repository stats
        uses: jgehrcke/github-repo-stats@306db38ad131cab2aa5f2cd3062bf6f8aa78c1aa # v1.4.2
        with:
          ghtoken: ${{ steps.app-token.outputs.token }}
          ghpagesprefix: https://bookish-fishstick-m61kqvo.pages.github.io/
